node {
  name: "X"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 256
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
node {
  name: "RELU_1_reshape_TPC_out1"
  op: "StaticReshape"
  input: "X"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "0"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "X  |  Sizes = [256]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1024, 4]  |  data = 0, sizeInBytes = 1024  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x40000000000  |  userMemorySection(type=Persistent, id=4)  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "_reshaped_175  |  Sizes = [4,64]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1024, 256, 4]  |  data = 0, sizeInBytes = 1024  |  isAliased = X, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "RELU_1_optimized"
  op: "relu_f32"
  input: "RELU_1_reshape_TPC_out1"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "1"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "_reshaped_175  |  Sizes = [4,64]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1024, 256, 4]  |  data = 0, sizeInBytes = 1024  |  isAliased = X, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "_reshaped_176  |  Sizes = [4,64]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1024, 256, 4]  |  data = 0, sizeInBytes = 1024  |  location = in DRAM  |  dramOffset = 0x0  |  "
    }
  }
}
node {
  name: "RELU_2_optimized"
  op: "relu_f32"
  input: "RELU_1_optimized"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "2"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "_reshaped_176  |  Sizes = [4,64]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1024, 256, 4]  |  data = 0, sizeInBytes = 1024  |  location = in DRAM  |  dramOffset = 0x0  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "_reshaped_180  |  Sizes = [4,64]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1024, 256, 4]  |  data = 0, sizeInBytes = 1024  |  isAliased = Y, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
}
node {
  name: "RELU_2_reshape_TPC_out0"
  op: "StaticReshape"
  input: "RELU_2_optimized"
  attr {
    key: "Bundle_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "Exec_idx"
    value {
      s: "3"
    }
  }
  attr {
    key: "Op_idx"
    value {
      s: "N/A"
    }
  }
  attr {
    key: "inputTensor:0"
    value {
      s: "_reshaped_180  |  Sizes = [4,64]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1024, 256, 4]  |  data = 0, sizeInBytes = 1024  |  isAliased = Y, type = alias, offset: 0  |  location = in DRAM  |  "
    }
  }
  attr {
    key: "outputTensor:0"
    value {
      s: "Y  |  Sizes = [256]  |  float32  |  expBias = 0, scale = 1  |    |  ModelParam = 0  |  strides = [1024, 4]  |  data = 0, sizeInBytes = 1024  |  isPersistent  |  location = in DRAM  |  dramOffset = 0x50000000000  |  userMemorySection(type=Persistent, id=5)  |  "
    }
  }
}
node {
  name: "Y"
  op: "OutputTensor"
  input: "RELU_2_reshape_TPC_out0"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 256
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
      }
    }
  }
  attr {
    key: "synDataType"
    value {
      s: "float32"
    }
  }
}
